### ISSUE TITLE
confirm we have all the gps tracks and clip them so they are on the stream

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#18]
May be another couple tracks for me on Fern that show me get to 16603769?  Same with the section I did downstream on Fern... 

Several tracks are loops showing person walking out to road through bush or on other road.  Best to clip those so that the symbology on the maps is cleaner

**Comment by Mateo9569** [comment]
Good call. Parsnip was the first time I ever clipped tracks so it's a bit choppy. I forgot that we kind of split up on the Fern Creek survey. You went further ahead of me upstream to get to 16601271 and then you did an extra section downstream that I didn't. I combined our downstream tracks and added the extra section upstream. You meant to say 16601271 instead of 16603769 right? Here's the corrected tracks for Fern shown in Q.

![image](https://user-images.githubusercontent.com/99455166/219813137-eba7ee89-e075-45b1-9175-5b05d4fd4ca0.png)
