### ISSUE TITLE
Photos for 125261 us 3 and 4 are in the wrong place on the map

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2022_reporting#27]
Not entirely sure what's happening here. These two are Al's photos so the coordinates were already in the metadata.

**Comment by NewGraphEnvironment** [comment]
if it is not an issue with a join to the gps required to due a neato google phone it could be that the photos were taken before the`timestamp` app recognized where it was.  This is only likely the case if it is the first photo at a site. Otherwise it would be near where the last photo in the site was taken.
