### ISSUE TITLE
Arctic 125000 site updates

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2022_reporting#46]
- [x] says currently there are no fish known there but we sampled lots over the years
- [x] map of old growth areas
- [x] details of why plans changed
- [x] Need to do PR in bcfishpass so that crossing ties to stream

**Comment by NewGraphEnvironment** [comment]
- [ ] site was reassessed in 2022 vs 2021...
- [ ] watershed area not accurate? 
- [ ] tables need scroll off?

**Comment by Mateo9569** [comment]
Notes from slack:
Old growth layer is in the shared project.  Plans changed because of old growth referrals. Gov has asked licensees to defer harvest of these areas until "partners develop a new approach for old growth forest management."
https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/old-growth-forests/deferral-areas

Licensees are reimbursed for costs related to improvements to roads through reduce stumpage through the Timber Appraisal process. Sinclar has put 700,000 tons3 (need to confirm number) of timber harvest beyond 125000 on the back burner due to the defferals.  Could use a simple figure in the memo to show this (use figure dimensions and build in shared project)
We should include some detail and references in our reporting on both the old growth deferral (Forestry District Specific I believe) situation as well as the Timber Appraisal system.

**Comment by NewGraphEnvironment** [comment]
remove the 125000 watershed because it is incorrect and not technically a phase 2 site. could use it for the phase 3 object though...

**Comment by NewGraphEnvironment** [comment]
- [ ] note that RB over 60mm were tagged
- [ ] point to data file for pit tagging information

**Comment by NewGraphEnvironment** [comment]
not going to worry about the watershed object
